import type { Exercise } from './types';

export const exercises: Exercise[] = [
  // Brust (chest)
  { name: 'Bankdrücken (Langhantel)', muscleGroup: 'chest' },
  { name: 'Bankdrücken (Kurzhantel)', muscleGroup: 'chest' },
  { name: 'Schrägbankdrücken (Langhantel)', muscleGroup: 'chest' },
  { name: 'Schrägbankdrücken (Kurzhantel)', muscleGroup: 'chest' },
  { name: 'Negativ-Bankdrücken', muscleGroup: 'chest' },
  { name: 'Fliegende (Kurzhantel)', muscleGroup: 'chest' },
  { name: 'Fliegende (Schrägbank)', muscleGroup: 'chest' },
  { name: 'Cable Crossover', muscleGroup: 'chest' },
  { name: 'Cable Crossover (tief)', muscleGroup: 'chest' },
  { name: 'Cable Crossover (hoch)', muscleGroup: 'chest' },
  { name: 'Butterfly Maschine', muscleGroup: 'chest' },
  { name: 'Dips (Brust)', muscleGroup: 'chest' },
  { name: 'Liegestütze', muscleGroup: 'chest' },
  { name: 'Chest Press Maschine', muscleGroup: 'chest' },
  { name: 'Schrägbank Chest Press Maschine', muscleGroup: 'chest' },
  { name: 'Landmine Press', muscleGroup: 'chest' },
  // Rücken (back)
  { name: 'Klimmzüge (breit)', muscleGroup: 'back' },
  { name: 'Klimmzüge (eng)', muscleGroup: 'back' },
  { name: 'Klimmzüge (Untergriff)', muscleGroup: 'back' },
  { name: 'Klimmzüge (neutral)', muscleGroup: 'back' },
  { name: 'Klimmzüge (unterstützt)', muscleGroup: 'back' },
  { name: 'Latzug (breit, Obergriff)', muscleGroup: 'back' },
  { name: 'Latzug (eng, Untergriff)', muscleGroup: 'back' },
  { name: 'Latzug (neutral, eng)', muscleGroup: 'back' },
  { name: 'Latzug (V-Griff)', muscleGroup: 'back' },
  { name: 'Latzug (einarmig)', muscleGroup: 'back' },
  { name: 'Rudern (Langhantel, Obergriff)', muscleGroup: 'back' },
  { name: 'Rudern (Langhantel, Untergriff)', muscleGroup: 'back' },
  { name: 'Rudern (Kurzhantel, einarmig)', muscleGroup: 'back' },
  { name: 'Rudern (Kabelzug, eng)', muscleGroup: 'back' },
  { name: 'Rudern (Kabelzug, breit)', muscleGroup: 'back' },
  { name: 'Rudern (Kabelzug, V-Griff)', muscleGroup: 'back' },
  { name: 'Rudern (Kabelzug, einarmig)', muscleGroup: 'back' },
  { name: 'Rudern (Maschine, eng)', muscleGroup: 'back' },
  { name: 'Rudern (Maschine, breit)', muscleGroup: 'back' },
  { name: 'T-Bar Rudern', muscleGroup: 'back' },
  { name: 'T-Bar Rudern (eng)', muscleGroup: 'back' },
  { name: 'Pendlay Row', muscleGroup: 'back' },
  { name: 'Seal Row', muscleGroup: 'back' },
  { name: 'Meadows Row', muscleGroup: 'back' },
  { name: 'Kreuzheben', muscleGroup: 'back' },
  { name: 'Face Pulls', muscleGroup: 'back' },
  { name: 'Hyperextensions', muscleGroup: 'back' },
  { name: 'Pullover (Kurzhantel)', muscleGroup: 'back' },
  { name: 'Pullover (Kabelzug)', muscleGroup: 'back' },
  { name: 'Straight Arm Pulldown', muscleGroup: 'back' },
  { name: 'Good Mornings', muscleGroup: 'back' },
  // Schultern (shoulders)
  { name: 'Schulterdrücken (Langhantel)', muscleGroup: 'shoulders' },
  { name: 'Schulterdrücken (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Schulterdrücken (Maschine)', muscleGroup: 'shoulders' },
  { name: 'Schulterdrücken (Smith-Maschine)', muscleGroup: 'shoulders' },
  { name: 'Arnold Press', muscleGroup: 'shoulders' },
  { name: 'Push Press', muscleGroup: 'shoulders' },
  { name: 'Seitheben (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Seitheben (Kabelzug)', muscleGroup: 'shoulders' },
  { name: 'Seitheben (Maschine)', muscleGroup: 'shoulders' },
  { name: 'Frontheben (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Frontheben (Langhantel)', muscleGroup: 'shoulders' },
  { name: 'Frontheben (Kabelzug)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flys (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flys (Maschine)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flys (Kabelzug)', muscleGroup: 'shoulders' },
  { name: 'Aufrechtes Rudern (Langhantel)', muscleGroup: 'shoulders' },
  { name: 'Aufrechtes Rudern (Kabelzug)', muscleGroup: 'shoulders' },
  { name: 'Aufrechtes Rudern (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Kurzhantel)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Langhantel)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Maschine)', muscleGroup: 'shoulders' },
  { name: 'Lu Raises', muscleGroup: 'shoulders' },
  // Beine (legs)
  { name: 'Kniebeugen (Langhantel)', muscleGroup: 'legs' },
  { name: 'Kniebeugen (Smith-Maschine)', muscleGroup: 'legs' },
  { name: 'Frontkniebeugen', muscleGroup: 'legs' },
  { name: 'Beinpresse (45°)', muscleGroup: 'legs' },
  { name: 'Beinpresse (horizontal)', muscleGroup: 'legs' },
  { name: 'Beinpresse (einbeinig)', muscleGroup: 'legs' },
  { name: 'Hack Squat', muscleGroup: 'legs' },
  { name: 'Pendel Squat', muscleGroup: 'legs' },
  { name: 'Ausfallschritte (Langhantel)', muscleGroup: 'legs' },
  { name: 'Ausfallschritte (Kurzhantel)', muscleGroup: 'legs' },
  { name: 'Ausfallschritte (gehend)', muscleGroup: 'legs' },
  { name: 'Bulgarian Split Squats', muscleGroup: 'legs' },
  { name: 'Rumänisches Kreuzheben (Langhantel)', muscleGroup: 'legs' },
  { name: 'Rumänisches Kreuzheben (Kurzhantel)', muscleGroup: 'legs' },
  { name: 'Sumo Kreuzheben', muscleGroup: 'legs' },
  { name: 'Beinstrecker', muscleGroup: 'legs' },
  { name: 'Beinbeuger (liegend)', muscleGroup: 'legs' },
  { name: 'Beinbeuger (sitzend)', muscleGroup: 'legs' },
  { name: 'Wadenheben (stehend)', muscleGroup: 'legs' },
  { name: 'Wadenheben (sitzend)', muscleGroup: 'legs' },
  { name: 'Wadenheben (Beinpresse)', muscleGroup: 'legs' },
  { name: 'Hip Thrust (Langhantel)', muscleGroup: 'legs' },
  { name: 'Hip Thrust (Maschine)', muscleGroup: 'legs' },
  { name: 'Goblet Squats', muscleGroup: 'legs' },
  { name: 'Hip Abductor', muscleGroup: 'legs' },
  { name: 'Hip Adductor', muscleGroup: 'legs' },
  { name: 'Step Ups', muscleGroup: 'legs' },
  { name: 'Sissy Squats', muscleGroup: 'legs' },
  { name: 'Beinpresse (eng)', muscleGroup: 'legs' },
  { name: 'Beinpresse (breit)', muscleGroup: 'legs' },
  { name: 'Glute Kickback (Maschine)', muscleGroup: 'legs' },
  { name: 'Nordic Hamstring Curl', muscleGroup: 'legs' },
  // Arme (arms)
  { name: 'Bizeps Curls (Langhantel)', muscleGroup: 'arms' },
  { name: 'Bizeps Curls (SZ-Stange)', muscleGroup: 'arms' },
  { name: 'Bizeps Curls (Kurzhantel)', muscleGroup: 'arms' },
  { name: 'Bizeps Curls (Kurzhantel, sitzend)', muscleGroup: 'arms' },
  { name: 'Bizeps Curls (Kabelzug)', muscleGroup: 'arms' },
  { name: 'Bizeps Curls (Maschine)', muscleGroup: 'arms' },
  { name: 'Hammer Curls', muscleGroup: 'arms' },
  { name: 'Hammer Curls (Kabelzug, Seil)', muscleGroup: 'arms' },
  { name: 'Konzentrationscurls', muscleGroup: 'arms' },
  { name: 'Preacher Curls (SZ-Stange)', muscleGroup: 'arms' },
  { name: 'Preacher Curls (Kurzhantel)', muscleGroup: 'arms' },
  { name: 'Preacher Curls (Maschine)', muscleGroup: 'arms' },
  { name: 'Spider Curls', muscleGroup: 'arms' },
  { name: 'Incline Curls', muscleGroup: 'arms' },
  { name: 'Cross-Body Hammer Curls', muscleGroup: 'arms' },
  { name: 'Trizeps Pushdown (Stange)', muscleGroup: 'arms' },
  { name: 'Trizeps Pushdown (Seil)', muscleGroup: 'arms' },
  { name: 'Trizeps Pushdown (V-Griff)', muscleGroup: 'arms' },
  { name: 'Trizeps Pushdown (einarmig)', muscleGroup: 'arms' },
  { name: 'French Press (SZ-Stange)', muscleGroup: 'arms' },
  { name: 'French Press (Kurzhantel)', muscleGroup: 'arms' },
  { name: 'Overhead Trizeps Extension (Kabelzug)', muscleGroup: 'arms' },
  { name: 'Overhead Trizeps Extension (Kurzhantel)', muscleGroup: 'arms' },
  { name: 'Dips (Trizeps)', muscleGroup: 'arms' },
  { name: 'Kickbacks (Kurzhantel)', muscleGroup: 'arms' },
  { name: 'Kickbacks (Kabelzug)', muscleGroup: 'arms' },
  { name: 'Close-Grip Bankdrücken', muscleGroup: 'arms' },
  { name: 'JM Press', muscleGroup: 'arms' },
  { name: 'Unterarm Curls (Obergriff)', muscleGroup: 'arms' },
  { name: 'Unterarm Curls (Untergriff)', muscleGroup: 'arms' },
  // Core
  { name: 'Crunches', muscleGroup: 'core' },
  { name: 'Plank', muscleGroup: 'core' },
  { name: 'Side Plank', muscleGroup: 'core' },
  { name: 'Hanging Leg Raises', muscleGroup: 'core' },
  { name: 'Knieheben (hängend)', muscleGroup: 'core' },
  { name: 'Cable Crunches', muscleGroup: 'core' },
  { name: 'Russian Twist', muscleGroup: 'core' },
  { name: 'Ab Roller', muscleGroup: 'core' },
  { name: 'Beinheben (liegend)', muscleGroup: 'core' },
  { name: 'Sit-Ups', muscleGroup: 'core' },
  { name: 'Mountain Climbers', muscleGroup: 'core' },
  { name: 'Woodchoppers', muscleGroup: 'core' },
  { name: 'Pallof Press', muscleGroup: 'core' },
  { name: 'Dead Bug', muscleGroup: 'core' },
  { name: 'Decline Sit-Ups', muscleGroup: 'core' },
  { name: 'Dragon Flag', muscleGroup: 'core' },
  // Cardio
  { name: 'Laufband', muscleGroup: 'cardio' },
  { name: 'Crosstrainer', muscleGroup: 'cardio' },
  { name: 'Fahrrad Ergometer', muscleGroup: 'cardio' },
  { name: 'Rudergerät', muscleGroup: 'cardio' },
  { name: 'Stairmaster', muscleGroup: 'cardio' },
  { name: 'Seilspringen', muscleGroup: 'cardio' },
  { name: 'Assault Bike', muscleGroup: 'cardio' },
  { name: 'Schwimmen', muscleGroup: 'cardio' },
];

export function getExercisesByGroup(muscleGroup: string): Exercise[] {
  return exercises.filter((e) => e.muscleGroup === muscleGroup);
}

export function searchExercises(query: string): Exercise[] {
  const lower = query.toLowerCase();
  return exercises.filter((e) => e.name.toLowerCase().includes(lower));
}

export const muscleGroups = ['chest', 'back', 'shoulders', 'legs', 'arms', 'core', 'cardio'];
