import type { Exercise } from './types';

export const exercises: Exercise[] = [
  // Chest
  { name: 'Bench Press (Barbell)', muscleGroup: 'chest' },
  { name: 'Bench Press (Dumbbell)', muscleGroup: 'chest' },
  { name: 'Incline Bench Press (Barbell)', muscleGroup: 'chest' },
  { name: 'Incline Bench Press (Dumbbell)', muscleGroup: 'chest' },
  { name: 'Decline Bench Press (Barbell)', muscleGroup: 'chest' },
  { name: 'Dumbbell Flyes (Flat)', muscleGroup: 'chest' },
  { name: 'Dumbbell Flyes (Incline)', muscleGroup: 'chest' },
  { name: 'Cable Crossover (Low)', muscleGroup: 'chest' },
  { name: 'Cable Crossover (High)', muscleGroup: 'chest' },
  { name: 'Pec Deck Machine', muscleGroup: 'chest' },
  { name: 'Dips (Chest)', muscleGroup: 'chest' },
  { name: 'Push-Ups', muscleGroup: 'chest' },
  { name: 'Chest Press Machine', muscleGroup: 'chest' },
  { name: 'Incline Chest Press Machine', muscleGroup: 'chest' },
  { name: 'Landmine Press', muscleGroup: 'chest' },
  // Back
  { name: 'Pull-Ups (Wide)', muscleGroup: 'back' },
  { name: 'Pull-Ups (Close)', muscleGroup: 'back' },
  { name: 'Pull-Ups (Underhand)', muscleGroup: 'back' },
  { name: 'Pull-Ups (Neutral)', muscleGroup: 'back' },
  { name: 'Pull-Ups (Assisted)', muscleGroup: 'back' },
  { name: 'Lat Pulldown (Wide, Overhand)', muscleGroup: 'back' },
  { name: 'Lat Pulldown (Close, Underhand)', muscleGroup: 'back' },
  { name: 'Lat Pulldown (Neutral, Close)', muscleGroup: 'back' },
  { name: 'Lat Pulldown (V-Bar)', muscleGroup: 'back' },
  { name: 'Lat Pulldown (Single Arm)', muscleGroup: 'back' },
  { name: 'Barbell Row (Overhand)', muscleGroup: 'back' },
  { name: 'Barbell Row (Underhand)', muscleGroup: 'back' },
  { name: 'Dumbbell Row (Single Arm)', muscleGroup: 'back' },
  { name: 'Cable Row (Close)', muscleGroup: 'back' },
  { name: 'Cable Row (Wide)', muscleGroup: 'back' },
  { name: 'Cable Row (V-Bar)', muscleGroup: 'back' },
  { name: 'Cable Row (Single Arm)', muscleGroup: 'back' },
  { name: 'Machine Row (Close)', muscleGroup: 'back' },
  { name: 'Machine Row (Wide)', muscleGroup: 'back' },
  { name: 'T-Bar Row', muscleGroup: 'back' },
  { name: 'T-Bar Row (Close)', muscleGroup: 'back' },
  { name: 'Pendlay Row', muscleGroup: 'back' },
  { name: 'Seal Row', muscleGroup: 'back' },
  { name: 'Meadows Row', muscleGroup: 'back' },
  { name: 'Deadlift', muscleGroup: 'back' },
  { name: 'Face Pulls', muscleGroup: 'back' },
  { name: 'Hyperextensions', muscleGroup: 'back' },
  { name: 'Pullover (Dumbbell)', muscleGroup: 'back' },
  { name: 'Pullover (Cable)', muscleGroup: 'back' },
  { name: 'Straight Arm Pulldown', muscleGroup: 'back' },
  { name: 'Good Mornings', muscleGroup: 'back' },
  // Shoulders
  { name: 'Overhead Press (Barbell)', muscleGroup: 'shoulders' },
  { name: 'Overhead Press (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Overhead Press (Machine)', muscleGroup: 'shoulders' },
  { name: 'Overhead Press (Smith Machine)', muscleGroup: 'shoulders' },
  { name: 'Arnold Press', muscleGroup: 'shoulders' },
  { name: 'Push Press', muscleGroup: 'shoulders' },
  { name: 'Lateral Raise (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Lateral Raise (Cable)', muscleGroup: 'shoulders' },
  { name: 'Lateral Raise (Machine)', muscleGroup: 'shoulders' },
  { name: 'Front Raise (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Front Raise (Barbell)', muscleGroup: 'shoulders' },
  { name: 'Front Raise (Cable)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flyes (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flyes (Machine)', muscleGroup: 'shoulders' },
  { name: 'Reverse Flyes (Cable)', muscleGroup: 'shoulders' },
  { name: 'Upright Row (Barbell)', muscleGroup: 'shoulders' },
  { name: 'Upright Row (Cable)', muscleGroup: 'shoulders' },
  { name: 'Upright Row (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Dumbbell)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Barbell)', muscleGroup: 'shoulders' },
  { name: 'Shrugs (Machine)', muscleGroup: 'shoulders' },
  { name: 'Lu Raises', muscleGroup: 'shoulders' },
  // Legs
  { name: 'Squat (Barbell)', muscleGroup: 'legs' },
  { name: 'Squat (Smith Machine)', muscleGroup: 'legs' },
  { name: 'Front Squat', muscleGroup: 'legs' },
  { name: 'Leg Press (45°)', muscleGroup: 'legs' },
  { name: 'Leg Press (Horizontal)', muscleGroup: 'legs' },
  { name: 'Leg Press (Single Leg)', muscleGroup: 'legs' },
  { name: 'Hack Squat', muscleGroup: 'legs' },
  { name: 'Pendulum Squat', muscleGroup: 'legs' },
  { name: 'Lunges (Barbell)', muscleGroup: 'legs' },
  { name: 'Lunges (Dumbbell)', muscleGroup: 'legs' },
  { name: 'Walking Lunges', muscleGroup: 'legs' },
  { name: 'Bulgarian Split Squats', muscleGroup: 'legs' },
  { name: 'Romanian Deadlift (Barbell)', muscleGroup: 'legs' },
  { name: 'Romanian Deadlift (Dumbbell)', muscleGroup: 'legs' },
  { name: 'Sumo Deadlift', muscleGroup: 'legs' },
  { name: 'Leg Extension', muscleGroup: 'legs' },
  { name: 'Leg Curl (Lying)', muscleGroup: 'legs' },
  { name: 'Leg Curl (Seated)', muscleGroup: 'legs' },
  { name: 'Calf Raise (Standing)', muscleGroup: 'legs' },
  { name: 'Calf Raise (Seated)', muscleGroup: 'legs' },
  { name: 'Calf Raise (Leg Press)', muscleGroup: 'legs' },
  { name: 'Hip Thrust (Barbell)', muscleGroup: 'legs' },
  { name: 'Hip Thrust (Machine)', muscleGroup: 'legs' },
  { name: 'Goblet Squats', muscleGroup: 'legs' },
  { name: 'Hip Abductor', muscleGroup: 'legs' },
  { name: 'Hip Adductor', muscleGroup: 'legs' },
  { name: 'Step Ups', muscleGroup: 'legs' },
  { name: 'Sissy Squats', muscleGroup: 'legs' },
  { name: 'Leg Press (Close)', muscleGroup: 'legs' },
  { name: 'Leg Press (Wide)', muscleGroup: 'legs' },
  { name: 'Glute Kickback (Machine)', muscleGroup: 'legs' },
  { name: 'Nordic Hamstring Curl', muscleGroup: 'legs' },
  // Arms
  { name: 'Bicep Curls (Barbell)', muscleGroup: 'arms' },
  { name: 'Bicep Curls (EZ-Bar)', muscleGroup: 'arms' },
  { name: 'Bicep Curls (Dumbbell)', muscleGroup: 'arms' },
  { name: 'Bicep Curls (Dumbbell, Seated)', muscleGroup: 'arms' },
  { name: 'Bicep Curls (Cable)', muscleGroup: 'arms' },
  { name: 'Bicep Curls (Machine)', muscleGroup: 'arms' },
  { name: 'Hammer Curls', muscleGroup: 'arms' },
  { name: 'Hammer Curls (Cable, Rope)', muscleGroup: 'arms' },
  { name: 'Concentration Curls', muscleGroup: 'arms' },
  { name: 'Preacher Curls (EZ-Bar)', muscleGroup: 'arms' },
  { name: 'Preacher Curls (Dumbbell)', muscleGroup: 'arms' },
  { name: 'Preacher Curls (Machine)', muscleGroup: 'arms' },
  { name: 'Spider Curls', muscleGroup: 'arms' },
  { name: 'Incline Curls', muscleGroup: 'arms' },
  { name: 'Cross-Body Hammer Curls', muscleGroup: 'arms' },
  { name: 'Tricep Pushdown (Bar)', muscleGroup: 'arms' },
  { name: 'Tricep Pushdown (Rope)', muscleGroup: 'arms' },
  { name: 'Tricep Pushdown (V-Bar)', muscleGroup: 'arms' },
  { name: 'Tricep Pushdown (Single Arm)', muscleGroup: 'arms' },
  { name: 'Skull Crushers (EZ-Bar)', muscleGroup: 'arms' },
  { name: 'Skull Crushers (Dumbbell)', muscleGroup: 'arms' },
  { name: 'Overhead Tricep Extension (Cable)', muscleGroup: 'arms' },
  { name: 'Overhead Tricep Extension (Dumbbell)', muscleGroup: 'arms' },
  { name: 'Dips (Triceps)', muscleGroup: 'arms' },
  { name: 'Kickbacks (Dumbbell)', muscleGroup: 'arms' },
  { name: 'Kickbacks (Cable)', muscleGroup: 'arms' },
  { name: 'Close-Grip Bench Press', muscleGroup: 'arms' },
  { name: 'JM Press', muscleGroup: 'arms' },
  { name: 'Wrist Curls (Overhand)', muscleGroup: 'arms' },
  { name: 'Wrist Curls (Underhand)', muscleGroup: 'arms' },
  // Core
  { name: 'Crunches', muscleGroup: 'core' },
  { name: 'Plank', muscleGroup: 'core' },
  { name: 'Side Plank', muscleGroup: 'core' },
  { name: 'Hanging Leg Raises', muscleGroup: 'core' },
  { name: 'Hanging Knee Raises', muscleGroup: 'core' },
  { name: 'Cable Crunches', muscleGroup: 'core' },
  { name: 'Russian Twist', muscleGroup: 'core' },
  { name: 'Ab Roller', muscleGroup: 'core' },
  { name: 'Lying Leg Raises', muscleGroup: 'core' },
  { name: 'Sit-Ups', muscleGroup: 'core' },
  { name: 'Mountain Climbers', muscleGroup: 'core' },
  { name: 'Woodchoppers', muscleGroup: 'core' },
  { name: 'Pallof Press', muscleGroup: 'core' },
  { name: 'Dead Bug', muscleGroup: 'core' },
  { name: 'Decline Sit-Ups', muscleGroup: 'core' },
  { name: 'Dragon Flag', muscleGroup: 'core' },
  // Cardio
  { name: 'Treadmill', muscleGroup: 'cardio' },
  { name: 'Elliptical', muscleGroup: 'cardio' },
  { name: 'Stationary Bike', muscleGroup: 'cardio' },
  { name: 'Rowing Machine', muscleGroup: 'cardio' },
  { name: 'Stairmaster', muscleGroup: 'cardio' },
  { name: 'Jump Rope', muscleGroup: 'cardio' },
  { name: 'Assault Bike', muscleGroup: 'cardio' },
  { name: 'Swimming', muscleGroup: 'cardio' },
];

export function getExercisesByGroup(muscleGroup: string): Exercise[] {
  return exercises.filter((e) => e.muscleGroup === muscleGroup);
}

export function searchExercises(query: string): Exercise[] {
  const lower = query.toLowerCase();
  return exercises.filter((e) => e.name.toLowerCase().includes(lower));
}

export const muscleGroups = ['chest', 'back', 'shoulders', 'legs', 'arms', 'core', 'cardio'];
